FROM node:22-slim
WORKDIR /app

RUN apt-get update && apt-get install -y openssl --no-install-recommends && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci --legacy-peer-deps

COPY prisma ./prisma

CMD ["npx", "prisma", "migrate", "deploy"]
